// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PixelPlay.Models;

public partial class ComentariosProducto
{
    public int ComentarioId { get; set; }

    public int ProductoId { get; set; }

    public int UsuarioId { get; set; }

    public string Comentario { get; set; }

    public DateTime FechaComentario { get; set; }

    public virtual Producto Producto { get; set; }

    public virtual Usuario Usuario { get; set; }
}