// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PixelPlay.Models;

public partial class Usuario
{
    public int UsuarioId { get; set; }

    public string NombreUsuario { get; set; }

    public string CorreoElectronico { get; set; }

    public string Contrasena { get; set; }

    public string Rol { get; set; }

    public virtual ICollection<CarritoTemporal> CarritoTemporals { get; set; } = new List<CarritoTemporal>();

    public virtual ICollection<ComentariosProducto> ComentariosProductos { get; set; } = new List<ComentariosProducto>();

    public virtual ICollection<HistorialCompra> HistorialCompras { get; set; } = new List<HistorialCompra>();

    public virtual ICollection<Pedido> Pedidos { get; set; } = new List<Pedido>();
}